version: '3.8'

services:
  
  data_api:
    build:
      context: ./functions
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./functions:/functions
    env_file:
      - .env
    ports:
      - "8000:8000"

  flaskapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0

  spark-master:
    build:
      context: ./data
      dockerfile: Dockerfile
    image: spark-image
    command: ["start-master"]
    ports:
      - "8080:8080"  # Port de l'UI du maître Spark
    volumes:
      - ./data/spark-apps:/opt/spark-apps  # Pour les applications Spark
      - ./data/spark-data:/opt/spark-data  # Pour les datas Spark
  
  spark-worker:
    build:
      context: ./data
      dockerfile: Dockerfile
    image: spark-image
    command: ["start-worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master
    volumes:
      - ./data/spark-apps:/opt/spark-apps
      - ./data/spark-data:/opt/spark-data

