version: '3.8'

services:

  spark-master:
    build:
      context: ./data
      dockerfile: Dockerfile
    image: spark-image
    env_file:
      - .env
    ports:
      - "8080:8080"  # Port de l'UI du maître Spark
    volumes:
      - ./data:/app
      - ./data/spark-apps:/opt/spark-apps  # Pour les applications Spark
      - ./data/spark-data:/opt/spark-data  # Pour les datas Spark
      - ./data/key-booming-splicer-415918.json:/opt/spark-data/key-booming-splicer-415918.json

  spark-worker:
    build:
      context: ./data
      dockerfile: Dockerfile
    image: spark-image
    command: ["start-worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master
    volumes:
      - ./data/spark-apps:/opt/spark-apps
      - ./data/spark-data:/opt/spark-data

